# Generated by Django 5.2.14 on 2026-05-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_audio_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='audio_file',
            new_name='archivo_audio',
        ),
    ]
