# Generated by Django 5.2.14 on 2026-05-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_audio_file_post_archivo_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
